#! /bin/bash

uzbl_dir=${XDG_DATA_HOME:-$HOME/.local/share}/uzbl

function choose_session {
    cat \
        <(echo "new") \
        <(find $uzbl_dir/sessions/ -type f | xargs -I{} -n 1 basename {}) \
        | dmenu -l 50 -p "Which session?"
    [[ -z $session ]] && { echo "No session chosen" >&2; exit 2; }
}

action=$(echo -e "switch\nrestore\nsave\nnew\nexit" | dmenu -l 50)

case $action in
    switch)
        session=$(choose_session)
        uzbl-session save
        uzbl-session kill
        uzbl-session restore -s $session
        ;;
    restore)
        session=$(choose_session)
        uzbl-session restore -s $session
        ;;
    save)
        uzbl-session save
        ;;
    new)
        session=$(choose_session)
        uzbl-session save -s $session
        uzbl-session spawn
        ;;
    exit)
        uzbl-session save
        uzbl-session kill
        ;;
    *) echo "Invalid action: $action" >&2; exit 1; ;;
esac
