#! /bin/bash

uzbl_dir=${XDG_DATA_HOME:-$HOME/.local/share}/uzbl

function choose_session {
    cat \
        <(echo "new") \
        <(find $uzbl_dir/sessions/ -type f -printf '%P\n') \
        | dmenu -p "Which session?"
}

action=$(echo -e "switch\nrename\nrestore\nsave\nnew\nexit" | dmenu -p "$(cat $uzbl_dir/.session)")
action=${action//$'\n'}

case $action in
    switch)
        session=$(choose_session)
        [[ -z $session ]] && { echo "No session chosen" >&2; exit 2; }
        uzbl-session save
        uzbl-session kill
        uzbl-session restore -s $session
        ;;
    rename)
        session=$(choose_session)
        [[ -z $session ]] && { echo "No session chosen" >&2; exit 2; }
        uzbl-session delete
        uzbl-session save -s $session
        ;;
    restore)
        session=$(choose_session)
        [[ -z $session ]] && { echo "No session chosen" >&2; exit 2; }
        echo $session
        uzbl-session restore -s $session
        ;;
    save)
        uzbl-session save
        ;;
    new)
        session=$(choose_session)
        [[ -z $session ]] && { echo "No session chosen" >&2; exit 2; }
        uzbl-session save -s $session
        uzbl-session spawn
        ;;
    exit)
        uzbl-session save
        uzbl-session kill
        ;;
    *) echo "Invalid action: $action" >&2; exit 1; ;;
esac
