#! /bin/bash

source ${XDG_DATA_HOME:-$HOME/.local/share}/uzbl/scripts/session-manager/session_defines

action=$(echo -e "restore\nsave\nset" | dmenu -l 50)
[[ -z $action ]] && { echo "No action chosen" >&2; exit 1; }
session=$(cat \
    <([[ -e $session_file ]] && echo "current") \
    <(echo "new") \
    <(find $session_dir -type f | xargs -I{} -n 1 basename {}) \
    | dmenu -l 50 -p "Which session?")
[[ -z $session ]] && { echo "No session chosen" >&2; exit 1; }

${script_dir}/uzbl-session --$action $session
